### ISSUE TITLE
Can't get this working

### ISSUE THREAD

**Issue by iDVB** [schovi/react-iscroll#11]
I have a wrapper `TileSorter` CSS defined as:

```
  position: absolute;
  z-index: 1;
  top: 45px;
  bottom: 45px;
  left: 0;
  width: 1024px;
  background: #ccc;
  overflow: hidden;
```

and I have this as my view:

```
      <div className="TileSorter">
        <ReactIScroll
          iscroll={iScroll}
          options={iScrollOptions}
          onScrollStart={this._onScrollStart}
          scrollerStyle={{width: "200%"}}
        >
          {_.sortByOrder(tileArray, ['order'],['asc']).map((tile, i) => {
            return (
              <Tile key={tile.id}
                params= {this.props.params}
                index={i}
                id={tile.id}
                text={tile.text}
                isEditable = {isEditable}
                onMove={this.props.onMove}
                onDelete={this.props.onDelete}
              />
            );
          })}
          <TilePreview key="__preview" />
        </ReactIScroll>
      </div>
```

which looks like this...
![View](http://goo.gl/6GNQ7y)

I would expect it should horizontally scroll. however it does not. However the event `onScrollStart` seems to fire as expected.

Any ideas?

**Comment by schovi** [comment]
Sorry for ignoring.
Have you already solved it?
If not, try it with latest version. Or open example and try to put similliar content there, where horizontal scrolling works fine.

I am currently work on 1.0.0 version, where one topic is structure of html. 
Now component render one div, where IScroll is applied and another which wrap content.
My idea is drop second div and keep it simple and "raw" as possible :)

If you can write what can help you, or your suggestion how to use that i will be happy.

**Comment by schovi** [comment]
There is updated 1.0.0 version, if you can test it, it would be awesome. https://github.com/schovi/react-iscroll/pull/17

**Comment by schovi** [comment]
@iDVB Hi, any new status with this? :)

**Comment by cbravo** [comment]
Hey there schovi!  I was working on the project with @iDVB and first of all Thank you for developing this piece of software.  In our case we did solve our issue by applying a second div  to wrap the content like iscroll and that worked. We have not tried using your new version yet.

**Comment by schovi** [comment]
@cbravo ok. I guess new version will can help you, because it leave wrapping completely on you, so I guess it is more transparent and developer controller :)
