### ISSUE TITLE
react-dom not in package JSON

### ISSUE THREAD

**Issue by vinceprofeta** [schovi/react-iscroll#15]
Is there a reason react-dom is not included in the package JSON? When I try to build my project react-dom is missing.

**Comment by schovi** [comment]
`react` is just peerDepencency, because you can have custom build or any version.
And `react-dom` from my point of view is not necessary. You can have custom renderer (react-native react-svg or whatever). You can use this library without it and your application should decide what to do with that.

**Comment by josephfinlayson** [comment]
It is necessary

`Module not found: Error: Cannot resolve module 'react-dom' in /home/joe/www/frontend/node_modules/react-iscroll/dist`

**Comment by josephfinlayson** [comment]
Offending line in dist:

`var iScrollInstance = new iScroll(_reactDom2['default'].findDOMNode(this), options);`

**Comment by schovi** [comment]
@josephfinlayson My bad!
![Facepalm](http://i3.kym-cdn.com/entries/icons/facebook/000/000/554/facepalm.jpg)

**Comment by schovi** [comment]
https://github.com/schovi/react-iscroll/commit/c1e655161321c147a75703b80b4af6b31d131e4a
