### ISSUE TITLE
0.1.6 and above fails to run

### ISSUE THREAD

**Issue by 03c** [schovi/react-iscroll#18]
I have been having some problems with the later versions of react-iscroll.

I can get version 0.1.5 of react-iscroll to work, but anything later fails when I try to run the application.

_React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `Page`._
_Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `Page`._

I have been looking through the code differences between 0.1.5 and 0.1.6 and notice quite a few changes surrounding webpack and Babel. So I can only assume that this is the cause? That is assuming I have been looking at the correct commits on GitHub compared with the release npm packages.

I am using React 0.14.5 with Gulp 3.9.0 & Babel if that helps at all.

Have you ever had this error? Am I missing some Babel plugins perhaps?

**Comment by sbialobok** [comment]
I'm also running into this issue.  I had to revert back to 0.1.5

**Comment by 03c** [comment]
@sbialobok Just found the problem. I'm guessing it's the same for you.

Change 

`var ReactIScroll = require('react-iscroll');`

to

`var ReactIScroll = require('react-iscroll').default;`

Not the _default_ at the end.

**Comment by schovi** [comment]
@christoefar Do you have babel in your project? If yes, try `require('react-iscroll/src/react-iscroll')` it will require raw es2015 source.
Your error must came from babel which export modules in different way than normal. Or your building system cant handle `require('react-iscroll')` as default :)

**Comment by hew** [comment]
Yeah I played around with this for a while but I can't get it to work either. I see some divs being created but no functionality occurring.

**Comment by schovi** [comment]
@hew Can you try this branch https://github.com/schovi/react-iscroll/tree/feature/update-dev-dependencies with updated dev dependencies.

**Comment by schovi** [comment]
Similar problem in this issue https://github.com/schovi/react-iscroll/issues/16
Was solved.
