### ISSUE TITLE
Why no support for react 0.14.x

### ISSUE THREAD

**Issue by stlouisweb** [schovi/react-iscroll#20]
I was wonder why the react dependency is pinned down to > 0.13.0 and < 0.14.0 versions? I'm trying to use this package with Meteor which uses react 0.14.7.

Are there plans to update the package? are there any known issues if I were to fork it and require react v0.14.7 instead?

**Comment by mcrider** [comment]
The dependency is `"react": ">=0.13.0 <=0.14.x"` -- so that includes any 0.14 version.

**Comment by stlouisweb** [comment]
oh, so it is, carry on.. :)
