### ISSUE TITLE
iscroll-probe  onScroll Event not work

### ISSUE THREAD

**Issue by 2857** [schovi/react-iscroll#26]
onScroll  event not work . and i bind the event correctly, except onScroll, other events work correctly

```
            <ReactIScroll iScroll={iScroll}
                  options={this.props.options}
                  onScrollStart={::this.onScrollStart}
                  onScrollCancel={::this.onScrollCancel}
                  onScrollStart={::this.onScrollStart}
                  onScroll={::this.onScroll}
                  onScrollEnd={::this.onScrollEnd}>
```

**Comment by 2857** [comment]
I knew the reason!!! cuz i didn't set the probetype 

`
probeType: 2 always executes the scroll event except during momentum and bounce. This resembles the native onScroll event.
`

**Comment by schovi** [comment]
@aliencyl7 Thanks for self resolving :)
