### ISSUE TITLE
how to disable react-iscroll

### ISSUE THREAD

**Issue by 2857** [schovi/react-iscroll#27]
in iscroll , using iscroll.disable, but in the react-iscroll, how to disable iscroll

**Comment by schovi** [comment]
@aliencyl7: Is there any documentation for that? On official page is no reference to that http://iscrolljs.com/

**Comment by 2857** [comment]
thx ~ i ve fixed it ~~~~

**Comment by Inoir** [comment]
Also its closed.. would be nice feature!
Was also looking for possibility to deactivate iscroll and activate it again.
Would be nice to have a simple REACT solution. Something like an "active" property should do all.
