### ISSUE TITLE
How to update options?

### ISSUE THREAD

**Issue by Benvorth** [schovi/react-iscroll#32]
... after the react-iscroll was rendered on DOM? For example I want to disable `scrollY` under certain conditions and re-enable it later. Binding the options=... to a state variable didn't work...

**Comment by schovi** [comment]
@Benvorth react-iscroll should reinitialize iscroll itself when options changed. It was build with this feature in mind. Have to test it somehow.

**Comment by schovi** [comment]
@Benvorth Improved example file to show how to do it. https://github.com/schovi/react-iscroll/commit/d9601948b92d191b64f5ab35b26e268e70a9e477?diff=unified#diff-9dc42c58804e2841c5330a81a75b977bR77

Key is `Object.assign({}, currentOptions, changedOptions)`. That mean, you have to create new object. Inside react-iscroll I do not compare each property separately, so If you just modify existing object it wont update component and wont refresh iscroll with new options.

I will take I look if I comparing can support changing of properties in options.

**Comment by peanuts6** [comment]
scroll event don't trigger
