### ISSUE TITLE
 iScroll events onScroll not work

### ISSUE THREAD

**Issue by gmonking** [schovi/react-iscroll#39]
```
  <ReactIScroll iScroll={iScroll} options={{mouseWheel: true}} onScroll={function(){console.log(1)}} >
    <div>
      ...
    </div>
  </ReactIScroll>
```

the onScroll callback function not work,

**Comment by schovi** [comment]
Hi, do you have iscroll probe version? It is only one with onacroll support

**Comment by Inoir** [comment]
you need to define the probe type you want to use in the options. Had same issue and only that worked for me.

so in your example:

` <ReactIScroll iScroll={iScroll} options={{mouseWheel: true, probeType: 1}} onScroll={function(){console.log(1)}} >
    <div>
      ...
    </div>
  </ReactIScroll>`

@schovi 
would be nice if there is an possibilty to tell iscroll to use at least type 1 if there is the probe version passed in react component?!

**Comment by Joudee** [comment]
@Inoir It didn't work!

**Comment by schovi** [comment]
@Inoir updated README with this info https://github.com/schovi/react-iscroll/blob/master/README.md#faqs

Will think if I can do the checking.
