### ISSUE TITLE
can't Scroll horizontal

### ISSUE THREAD

**Issue by Benvorth** [schovi/react-iscroll#4]
Even if I add `freeScroll: true` or `scrollX: true` to the options I can't get react-iscroll to scroll horizontal. Is there a special setting for it?

**Comment by schovi** [comment]
@Benvorth It should works same as original iScroll. Do you have any playground where we can debug it?

**Comment by mofas** [comment]
Have same issue.

**Comment by wer** [comment]
Me too same issue

**Comment by schovi** [comment]
Updated example  https://github.com/schovi/react-iscroll/commit/1ea543f0fbedc4f44ab1f60a2a2e78727ac85d68

Problem is that IScroll component wrap iscroll element itself into one more div which solve overflow hidden and other necessary styling. Maybe this should not be here, or only as option?

**Comment by Benvorth** [comment]
You have to add 'scrollerStyle={{width: '200%'}}' as option, without it the horizontal scrollbar will not appear. Now it works, thank you!
