### ISSUE TITLE
While scrolling, if the mouse gets released outside of the frame the state remains pressed

### ISSUE THREAD

**Issue by zeachco** [schovi/react-iscroll#41]
I know this is more likely a browser issue but this is a nice improvment that could be acheived: could we reset the state or retest the mouse down states when mouse is out of the content?

you can reproduce on https://codepen.io/jakob-e/pen/wBmgYb by clicking the content to scroll and release mouse in the editor area since the preview is in a iframe

maybe somthing using code such as 
```javascript
document.body.addEventListener('mouseleave', function() {
  alert('left body we must recalculate on next mousemove if we still press the mouse button');
})
```
would help fixing this

**Comment by schovi** [comment]
@zeachco This si issue for original scroll library https://github.com/cubiq/iscroll

**Comment by zeachco** [comment]
Thanks for redirecting
