### ISSUE TITLE
'Uncaught ReferenceError: eventNames is not defined'

### ISSUE THREAD

**Issue by ChristiaanScheermeijer** [schovi/react-iscroll#5]
Hi,

There is a Uncaught ReferenceError thrown from https://github.com/schovi/react-iscroll/blob/master/src/react-iscroll.js#L180

**Comment by schovi** [comment]
I guess this is fixed with https://github.com/schovi/react-iscroll/pull/2

**Comment by jamesseanwright** [comment]
Hey dude,

When do you plan on releasing this fix? I can point to this repo directly in my `package.json` file, but I'd rather be able to point to a fixed version.

Thanks!

**Comment by jamesseanwright** [comment]
In fact, to keep things stable, I'm pointing to my own fork for now. However, a new release would still be awesome. Thank you.

**Comment by schovi** [comment]
@jamesseanwright Totally forgot! It is up to date.

Thanks

**Comment by jamesseanwright** [comment]
Excellent, I shall update my reference tomorrow. Cheers :)
