### ISSUE TITLE
1.1.3 causing 'npm ERR! cb() never called!'

### ISSUE THREAD

**Issue by sinn1** [schovi/react-iscroll#54]
We have "react-iscroll": "^1.1.0" in our package.json (allow minor version upgrades) and the new version (1.1.3) results in this error during npm install. 

Using "react-iscroll": "1.1.2" instead.

**Comment by zaggaz** [comment]
+1

**Comment by gbk** [comment]
+1

**Comment by alex-mm** [comment]
+1

**Comment by moxiaohe** [comment]
+1

**Comment by fengsx** [comment]
+1

**Comment by yize** [comment]
+1

**Comment by yukap6** [comment]
+1

**Comment by yanbingbing** [comment]
+1

**Comment by wushanchao** [comment]
+1

**Comment by eJayYoung** [comment]
+1

**Comment by pplgin** [comment]
+1

**Comment by schovi** [comment]
Thx for report. Can you add more info, where this error is thrown? During `npm install`, or somewhere else? I am trying simulate this on new project and can't reach that state. If you have working example or know how to fix it give me hint.

**Comment by sinn1** [comment]
Yea on npm install. Delete node_modules folder and try npm install. Error should be thrown.

**Comment by schovi** [comment]
Got it. But what the hell :)

**Comment by schovi** [comment]
Fixed with 1.1.4 https://github.com/schovi/react-iscroll/commit/8828f5e29c43c1fe832e57990cf38bfe49c4a780

Problem was, that I published package with `yarn` instead of `npm`
