### ISSUE TITLE
Convert source into babel.js

### ISSUE THREAD

**Issue by schovi** [schovi/react-iscroll#7]
Hi,

I tried to make source of this module in modern ES6/7/JSX babel code  https://github.com/schovi/react-iscroll/tree/feature/babel :)

For npm publishing it will be compiled into compatible ES5 code.

Can anybody give me feedback if this is generally good way how to write javascript today, or it is still large overhead with lot of problems like debugging, size and maybe performance?

**Comment by jamesseanwright** [comment]
I've just published an npm module that was written in ES6 and compiles to ES5 via Babel. Personally this is the approach I want to take forward as:
1. Once io.js has fully merged with Node.js, everything should just work!
2. Native Harmony support is gradually improving

Thus, Babel has allowed me to avoid having to rewrite my library in ES6 at a later date. In terms of debugging, the browser makes it easy through its support of source maps, allowing you to set breakpoints on your ES6 code! Node.js doesn't support source maps natively, but there's a [third party library](https://github.com/evanw/node-source-map-support) to achieve this.

I personally haven't noticed any performance bottlenecks, but I'll keep my eye on things.

As a heads up, it's a good practice to include a `.npmignore` file to forcibly exclude source files. Mine is:

```
src
tests
__tests.js
README.md
```

My compiled ES5 code lives in a `dist` directory, and in my `package.json` I set my entry point to `dist/index.js`.

Happy ES6ing ;)

**Comment by jamesseanwright** [comment]
Just seen your branch and you're already a step ahead of me ;) In that case, my other points still apply. In terms of performance, looks like the Babel guys have [really been proactive](https://github.com/babel/babel/issues/476)!

**Comment by schovi** [comment]
I just followed tutorial http://mammal.io/articles/using-es6-today/ :)

**Comment by yordis** [comment]
@schovi I created this for my own components https://github.com/React-UI/generator-react-ui-component probably that will work for you, so far no complains.

**Comment by schovi** [comment]
Done https://github.com/schovi/react-iscroll/pull/8

Thanks for tips.
